### PR TITLE
Gulp 4 upgrade

### PR DESCRIPTION
**Pull request by Dan503**
Gulp 4 is a far more pleasant platform to work on than Gulp 3 is. The gulp.series() and gulp.parallel() functions allow tasks to be made more modular. Instead of listing task dependencies, you state what order tasks should be carried out in.

Gulp 4 also requires task completion to be explicitly announced either by returning a source stream (`gulp.src()`), returning a promise, or by explicitly announcing the `done()` function. This immensely helps people that are trying to make tasks run in series (eg. copying files to a server after all files have finished compiling).

Gulp 3 is also really bad at understanding when files have finished being created. If you list task A as a dependency for task B and task B requires a file that task A generates, task B will usually fail since task A states that it is done before it has finished writing the file to the file system. That is not an issue in gulp 4 since gulp.series() will always wait for the file to be fully written before announcing that the task is done. That is based on my experience anyway. This Gulp 3 issue may just be down to how I was writing my Gulp files but nonetheless, it has always been a nightmare for me to get tasks to run in series on Gulp 3 and it has never been an issue for me in Gulp 4.

I'm not sure how to actually test the changes I've made. Based on what I know of Gulp 4 these changes should work but since I can't test them I'm not sure.

Gulp 4 isn't _officially_ released yet, however the popular "Foundation" framework is already using it in their frameworks. https://foundation.zurb.com/
I don't see why Yeogurt wouldn't be able to make the jump to Gulp 4 as well.

Given the issues with Gulp 3, I would say that even though Gulp 4 hasn't officially been released yet, I think Gulp 4 is actually a MORE stable platform than Gulp 3 is.

If you have never used Gulp 4 before, you may need to update your gulp CLI to compile the code.

````````
npm rm -g gulp
npm install -g gulp-cli
````````

More information on making the jump to Gulp 4 can be found here:
https://www.liquidlight.co.uk/blog/article/how-do-i-update-to-gulp-4/

Please upgrade to Gulp 4, it allows for a much nicer development experience and it makes the Yeogurt framework immensely easier to upgrade in future.

### CODE REVIEW

**Comment by larsonjj** [comment]
Hey @Dan503,

Thanks for the PR 👍. Definitely want to upgrade to Gulp 4, but need to hold off until the stable release. I'll keep this PR open for now and hopefully the Gulp devs will release v4 soon. Then I'd be happy to merge this in.

**Comment by Dan503** [comment]
Hi @larsonjj Gulp 4 has _**finally**_ been officially released!!!

https://www.npmjs.com/package/gulp

Gulp version 4.0.0

Can this get merged in now (after testing it works)? I don't know how to test the changes.

This would need to be released as a new major version bump. Many people will need to upgrade their gulp-cli to use Gulp 4.

**Comment by larsonjj** [comment]
Closing this in favor of #226. Thanks for the initial work on this @Dan503

**Comment by oninross** [comment]
I created a new Yeogurt project from scratch and its not yet gulp 4.  When I did do an npm audit, i needed to do a `npm install --save-dev gulp@4.0.2`.  And after that, this happened:

```
AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/rodrini/Desktop/yeogurt/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/rodrini/Desktop/yeogurt/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/rodrini/Desktop/yeogurt/gulpfile.babel.js:44:6)
    at Module._compile (module.js:653:30)
    at loader (/Users/rodrini/Desktop/yeogurt/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/rodrini/Desktop/yeogurt/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at execute (/usr/local/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp-cli/index.js:175:63)
    at Liftoff.execute (/usr/local/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:203:12)
    at module.exports (/usr/local/lib/node_modules/gulp-cli/node_modules/flagged-respawn/index.js:51:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:195:5)
```

**Pull request closed without merging**
