### PR TITLE
Issue #150: Minify CSS in the production

### PR DESCRIPTION
**Pull request by OnkelTem**
minifyCSS `{rebase: false}` probably needs some further work, but for now we have this: https://github.com/jakubpawlowicz/clean-css/issues/661

### CODE REVIEW

**Comment by larsonjj** [comment]
Hey @OnkelTem,

Thanks for the PR :+1: 

Could you make one change though?
Remove the import/require gulp-minify-css from each gulp task and use `plugin.minifyCss()` within the gulpif statement.

so:
```
.pipe(gulpif(args.production, minifyCSS({rebase: false})))
```

becomes:
```
.pipe(gulpif(args.production, plugins.minifyCss({rebase: false})))
```

This will be a bit cleaner and more consistent with the rest of the codebase.

**Comment by OnkelTem** [comment]
Sure!

**Comment by OnkelTem** [comment]
oops, something goes wrong - `plugins`  is not populated. digging

**Comment by larsonjj** [comment]
Great :+1: 

I will start testing this and if all is well, I will merge.

**Pull request merged**
