### PR TITLE
Code improvements

### PR DESCRIPTION
**Pull request by Dan503**
Code improvements in this pull request:

## Moving gulp tasks into a tasks folder

Needed for further enhancements later down the line. It means that we can have more than just gulp tasks housed in this gulp folder. This also makes upgrades to the Gulp config easier.

## Moving shared variables out into a separate file

This structure has multiple advantages:

- It is cleaner
- It doesn't require every property to be imported into every Gulp task file
- A gulp task in one file is able to run gulp tasks in a different file if needed.
- task dependencies are easier to manage

It is mainly just a more correct way to structure the code. It imports the variables it needs from a single file rather than passing them all down as props into every single file.

## Replacing path.join() with a simple join() helper function

`path.join()` does not work as expected if used in Gulp 4!

Do not use `path.join()` if using Gulp 4. It leads to a multitude of bugs. Use this simple helper function instead.

```js
const join = (...paths) => paths.join('/')
```

## Fix for broken clean task syntax

Arrow functions split across multiple lines need brackets to work.

I could have simplified it down to this:

```js
 gulp.task('clean', del([path.join(dirs.temporary), path.join(dirs.destination)]) );
```

I figured that keeping the function call there makes it easier for people less familiar with Gulp and JS to upgrade the task if needed.

## Adding "done" call to the watch task

Gulp 4 requires people to signal task completion. Task completion was not being signaled on the watch task.

The watch task is never truly "done" so I just call it at the end after all of the watchers have been initialized.

## Using native Object.assign() instead of lodash

There is no need to use Lodash when Object.assign() is a native way to do the exact same thing as what you were using Lodash for.

### CODE REVIEW

**Comment by Dan503** [comment]
If you saw the pull request via email, I have updated the description since then.

I accidentally hit `[enter]` to early when creating the pull request. 😖

**Comment by larsonjj** [comment]
Hey @Dan503,

Thanks so much for your work on this PR! (and for your continued interest in the project 😄). Due to #226 being such a massive rewrite of the generator and constant development over the past few days, I wasn't able to get this merged (Some pretty hair merge conflicts). Apologies for that.

The good news is that I was able to incorporate most of your suggestions:

- Tasks moved from `gulp/*` to `gulp/tasks/*`
- `gulp/utils.js` file to hold logic instead of passing data through function to each gulp task
- Adding `done()` to the watch task
- Using Object.assign instead of lodash's method

> NOTE: I didn't add the extra `join()` method proposed as I was able to make use of the `gulp.src`'s `cwd` option to achieve the same results.

Will be pushing `v.3.0.0` to npm soon. So you'll be able to try out all the new changes soon!

Cheers 🍻

**Comment by Dan503** [comment]
> NOTE: I didn't add the extra join() method proposed as I was able to make use of the gulp.src's cwd option to achieve the same results.

That makes me very nervous.

Trust me, you do not want to use `path.join` if you are using Gulp 4.

The Gulp will still compile but files will get sent to the wrong directories.

I *strongly* recommend using the `join()` helper function instead of `path.join()`. You will likely receive a huge number off issue complaints of things being sent to the wrong directories otherwise.

**Comment by larsonjj** [comment]
@Dan503,

Totally understand your concern. The thing that needs to be avoided in Gulp v4 with `path.join` is globbing (i.e. `**/**.js`). Including globs in a `path.join` will mess things up on Windows, so the recommended solution is to use the `cwd` option in `gulp.src`. So those are the changes I made (see for https://github.com/larsonjj/generator-yeogurt/blob/master/generators/app/templates/gulp/tasks/copy.js an example)

Definitely open to your proposed solution if problems do arise with the `path` module and `cwd` option, but we shouldn't need any extra `join` functions to handle the needed use cases at this time.

**Comment by Dan503** [comment]
I think it is still better to just use a `join()` helper function.

Think of it from the perspective of people unfamiliar with Gulp and the `path.join()` issue (likely to be a huge percentage of your users). Let's say this person wants to add additional functionality to the configuration.

When the user is looking at the code, it looks like `path.join()` is just doing what the `join()` helper function does. They make a new Gulp task but they leave off `cwd` because it seems like unnecessary extra code and they think it's ugly and they don't want to write that. Let's say they are also a Mac user so their buggy code seems to be working perfectly with no issues. They then delete the rest of the `cwd` parts to make the code look nicer and have code consistency across the project so there is no longer a Gulp task that has `cwd` in it. They continue adding more tasks using the same buggy technique. A new developer then gets put onto the project because time is running out and we need this done ASAP! This new dev is a Windows user so when they go to compile the code everything gets sent to the wrong locations. The Mac user has no idea what the problem is. He hasn't touched the Gulp files in months and completely forgot that he deleted all of the `cwd` bits. Since the Mac user can't replicate the issue, it's up to the windows user to fix the Mac user's broken code. The windows user always just uses the defaults when starting projects so they have no idea how Gulp works. They then have to waste a full day learning how Gulp works, trying to figure out what the problem is when they were supposed to be helping out on the development for a project that is in a critical state. Gulp doesn't give off any errors so it's extremely difficult to debug. Since the Mac user deleted all the `cwd` bits, there aren't any examples where the code works. They eventually figure out that `path.join()` was what the issue was and now they have to go through all the code and replace `path.join()` with whatever their custom equivalent ends up being. The windows user just wanted to help out with the project but now a critical project is an extra day behind schedule because you wanted to use `path.join()` instead of a `join()` helper function.

I had to go through the pain of figuring out the problem with `path.join()` the hard way. It was not fun. (The above is a hypothetical but highly likely scenario. It didn't happen to me.)

Aside from the reasons above, there are also developer experience reasons to switch:

It is also cleaner and easier to write `join()` rather than `path.join()`. `join()` is 6 characters and 1 autocomplete. `path.join()` is 11 characters, takes 2 autocompletes, and a full stop to write. It also requires `cwd` to be included whereas `join()` does not.

You can also select all of `join` with a single double click or a single `ctrl+➡️`. You have to click and drag the mouse to select all of `path.join()` or press `ctrl+➡️` twice (maybe 3 times due to the full stop) to get past it.

When importing them as well, `path.join()` requires a full extra line to be added whereas `join()` only requires an extra 4 character autocompleted value to be imported from `utils.js` with the rest of the utils.

Is that enough reasons to switch to a `join()` helper yet? 😓

**Pull request closed without merging**
